### ISSUE TITLE
 Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

### ISSUE THREAD

**Issue by C-Loftus** [coqui-ai/STT-examples#23]
I tried to run the python websocket example but I am getting an error. 
I cloned the repo and first did 
```
sudo docker build .
```
This succeeded. Then I did the following. It is possible I am misunderstanding the build process, but I am getting this error. 

```
$ sudo docker container run b6898d9a294d
TensorFlow: v2.2.0-24-g1c1b2b9
DeepSpeech: v0.8.2-0-g02e4c76
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2021-11-21 23:05:17.440646: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: /opt/deepspeech/model.tflite; No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/deepspeech/deepspeech_server/app.py", line 17, in <module>
    scorer_path=Path(conf["deepspeech.scorer"]).absolute().as_posix(),
  File "/opt/deepspeech/deepspeech_server/engine.py", line 30, in __init__
    self.model = Model(model_path=model_path)
  File "/usr/local/lib/python3.6/dist-packages/deepspeech/__init__.py", line 38, in __init__
    raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Error reading the proto buffer model file.' (0x3005)
``` 
I was wondering if a cpu-architecture check might be useful to have?
I am a bit stuck on how to fix this issue given, to my understanding, coqui uses its own fork of tensorflow.
Running it without the container 
```
python -m deepspeech_server.app
```
produces the same error
Thanks!

**Comment by C-Loftus** [comment]
I misinterpreted the error. Found answer here https://github.com/coqui-ai/STT/discussions/2010
